language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: kaCKQQLGpS26UQevgpdY74XVpgL0a/3q9FjdWbb37UmccVXJN1fQCailOuSMe67u4Qu3izCfSCGR9rl5w3R1MLepeCyjPZ6BdHuy3FJlEHbyrJXh/U7Fkqu3sCegb+FKJJqsGGv7t8vYGmJsOCnXIFqtuZ6Qd5/ndMu8XmwJ/JnldQskidqlWdgoQMbya60ywPA+1Slirm4Ps6i+qsDget/WJYSdkSl9KpudVsq8umcTktGbtUtu1xG9QYYITTcuA3O6qHrwHcNAL2mfxiA0rPijXRyGMqU1kluQS0giRJgnEt5ggBOkpZG/8XojNijbsoRB7qdWw7a2mt72z7gkofMMpIEuM7y+nOU22aXj9aAn9P9mqMOTgj46H/d6KSkRCSrILGL0J43u0Wvuo+yS8tHY+gjr67Wo7+xDlzhZ8BBzK/sOtPxt/Uk9dzYtSd8y3R8kOelrxOd25rghL1ZweE4t+L5rhimwrE8i1TaScJ4HTrGImOLwTQ1trT39HUUXVV6xIF9m1XKLl1LGs9K1mvLCoL/wMq+JqpBeAzbWKoPrTwaXkeVfVthFneyhqkfXSE4Q1ayvKT9ALiUpNtd5DOTQailJUz4Xl7QLSyt9K4Pp2mBAlBQn88SKFKPP+7xcfHCiee12wMcSPLrzfWqa8H8kbyqSvXSx+VZuTsa+QDE=
  app: shielded-mesa-98455
  on:
    repo: TreyLiebscher/shoppingIntegrationTest
